[package]
name = "signal"
version = "0.1.0"
authors = ["G1gg1L3s <mr.a678i@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"